### ISSUE TITLE
Return a promise

### ISSUE THREAD

**Issue by felixfbecker** [gulpjs/async-done#35]
I would like to use this manually and chain multiple calls.

**Comment by phated** [comment]
No. Sorry.

**Comment by felixfbecker** [comment]
Sorry to come back to this 2 years later, but It would be incredibly helpful for triggering other tasks in a watch task, e.g. 

```ts
export function copyFoo() {
    return gulp.src(fooFiles).pipe(gulp.dest(someDest))
}

export async function watchFoo() {
    await asyncDone(copyFoo())
    // ...maybe do more things...
    await new Promise((_, reject) => gulp.watch(fooFiles, copyFoo).on('error', reject))
}
```
Why can't we add this?

**Comment by demurgos** [comment]
With the great popularity of Promises and their integration to the language (including async syntax), I think it would improve the ergonomics of the lib regardless of the use case.

I believe that the main reason for the rejection of this feature is that Gulp still supports Node `0.10`, where promises don't exist. I believe that using native promises when available and falling back to Bluebird when needed may work.
Given the current API, promise support can be added in a non-breaking way: return a promise if there is no callback argument. This matches the behavior of many other APIs.

Thoughts on this @phated?

**Comment by phated** [comment]
This is completely the wrong way to be looking at gulp integration. This library isn't supposed to be used alone inside a gulp task. You're trying to change the purpose of this library.

**Comment by felixfbecker** [comment]
@phated in https://github.com/gulpjs/gulp/issues/755#issuecomment-198775161 you recommended to just call other task functions when a task needs to call another - but to do so, there needs to be a way to await the task with all the possible types a task can return. Using `async-done` seemed like the obvious choice to achieve this since it's what Gulp uses.

Besides that, this library can be very useful outside of gulp (if it wasn't, it could just be internal inside the gulp package)
