### ISSUE TITLE
npm test aborts due to lint style errors

### ISSUE THREAD

**Issue by BurtHarris** [gulpjs/async-done#38]
Now you've done it, got me interested enough to clone, build, and test. 👍      

Running the command `npm test` gives me 7 minor issues, and exits with failure.   They are all basically like this:

```
Invalid line break at test/streams.js :
     1 |'use strict';
---------------------^
     2 |
     3 |var expect = require('expect');


7 code style errors found.
```
I don't know your lint style, is it objecting to the semicolon, or something about the line break?

I'm on a Windows 10 machine if it matters, running node v6.10.3 and npm v5.0.3.

**Comment by BurtHarris** [comment]
Just checked, it's the CRLF style line endings that seem to be the issue.   Git seems to convert line endings to the local convention when I cloned the files, and stores them back in the repository in neutral form.   

I would suggest that based on this, having lint enforce this rule is heavy-handed unless something goes into the project telling git to not convert line endings.

**Comment by phated** [comment]
I'm open to a `.gitattributes` file that forces `text eol=lf` - feel free to submit.
