### ISSUE TITLE
Promise that resolves to Stream or ChildProcess?

### ISSUE THREAD

**Issue by apowers313** [gulpjs/async-done#50]
Would it be acceptable to have async-done wait on a Stream or a ChildProcess that is the result of a resolved promise?

Use case is like this:

``` js
async function myTask() {
    await someSetup();
    return gulp.src(/*...*/).pipe(/*...*/);
}
```

Happy to submit a PR if this is a good idea.

**Comment by phated** [comment]
You *really* **really** *really* don't want to combine different types of asynchronousity like that.  You'd be opening yourself to a world of bugs and other issues.

If you want to do this in gulp, just keep it simple:
```js
let config;

async function setup() {
    config = await someSetup();
}

const myTask = gulp.series(setup, function() {
    return gulp.src(/*...*/).pipe(/*...*/);
});
```
