### ISSUE TITLE
trying to trace through Gulp framework and what/where is "domain"?

### ISSUE THREAD

**Issue by cdbattags** [gulpjs/async-done#53]
Per this line:

https://github.com/gulpjs/async-done/blob/v1.3.2/index.js#L3

No idea how to trace this with nothing in `package.json`, no?

**Comment by phated** [comment]
That's a node core module 🤣

**Comment by cdbattags** [comment]
Whelp that's a new one for me...

Any concerns about it being deprecated?

https://nodejs.org/api/domain.html

**Comment by phated** [comment]
No concerns until they solve the thing that domains solve. They tried before and gave up.
